# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gym_id', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gym_id', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
                ('In_time', models.TimeField(blank=True, default='12:00:00', null=True)),
                ('Out_time', models.TimeField(blank=True, default='12:00:00', null=True)),
            ],
        ),
    ]
