# Generated by Django 4.2.7 on 2023-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='attendance',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
