# Generated by Django 4.2.7 on 2023-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0002_user_table_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='In_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='Out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
