# Generated by Django 4.2.7 on 2023-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_fee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_attendance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='trainer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fee_table',
            name='paid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
