# Generated by Django 4.2.7 on 2023-12-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0005_trainer_attendance_table_trainer_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_attendance_table',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer_attendance_table',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
