# Generated by Django 4.2.7 on 2023-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_alter_trainer_attendance_table_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
