# Generated by Django 4.2.7 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0007_finance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_table',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='finance_table',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
