# Generated by Django 4.2.7 on 2024-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0008_alter_finance_table_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
