# Generated by Django 4.2.7 on 2024-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0009_alter_user_table_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
