# Generated by Django 4.2.7 on 2024-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0010_register_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_table',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
