# Generated by Django 4.2.7 on 2024-01-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0011_trainer_table_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finance_table',
        ),
    ]
